Repository batocera-linux/batocera.linux, pull requests merged in 2020-03, with the labels that each got.

#1324 Fix a couple of boot error messages
  board/batocera/fsoverlay/etc/init.d/S12populateshare
  board/batocera/fsoverlay/etc/modules.conf
  package/batocera/core/batocera-system/Config.in
Labels: 5.25

#1331 lr-mame: version bump (0.219)
  batocera-Changelog
  package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
Labels: 5.25

#1318 Roshambo case
  batocera-Changelog
  package/batocera/Config.in
  package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife
  package/batocera/core/batocera-system/Config.in
  package/batocera/core/batocera-system/rockpro64/batocera.conf
  package/batocera/utils/roshambo-case/Config.in
  package/batocera/utils/roshambo-case/S14roshambo
  package/batocera/utils/roshambo-case/roshambo-case.mk
  package/batocera/utils/roshambo-case/roshambo-case.py
Labels: 5.26

#1334 Last minute fixes for 5.25
  board/batocera/rockpro64/linux-defconfig.config
  configs/batocera-miqi_defconfig
  configs/batocera-rockpro64_defconfig
  configs/batocera-tinkerboard_defconfig
  package/batocera/boot/rockpro64-blobs/rockpro64-blobs.mk
  package/batocera/utils/roshambo-case/S14roshambo
  package/batocera/utils/roshambo-case/roshambo-case.py
Labels: 5.25

#1339 wii: better fps
  package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
Labels: 5.26

#1336 update updates urls
  package/batocera/core/batocera-scripts/scripts/batocera-config
  package/batocera/core/batocera-scripts/scripts/batocera-es-swissknife
  package/batocera/core/batocera-scripts/scripts/batocera-es-thebezelproject
  package/batocera/core/batocera-scripts/scripts/batocera-es-theme
  package/batocera/core/batocera-scripts/scripts/batocera-install
  package/batocera/core/batocera-scripts/scripts/batocera-upgrade
Labels: 5.26

#1335 clean share links
  board/batocera/fsoverlay/recalbox/share
  board/batocera/fsoverlay/recalbox/share_init
Labels: 5.26

#1340 Fixed a bug in rare cases where a RA game has no success icons
  package/batocera/core/batocera-scripts/scripts/batocera-retroachievements-info
Labels: 5.26

#1328 Moonlight: fixed script, ported it to new theGamesDB JSON API
  package/batocera/core/batocera-scripts/scripts/batocera-moonlight
Labels: 5.26, don't merge

#1338 experimental: c20 and c128
  package/batocera/emulationstation/batocera-es-system/es_systems.yml
Labels: 5.26

#1322 bump: linapple-pie to linappleii
  package/batocera/Config.in
  package/batocera/core/batocera-configgen/configgen/configgen/batoceraFiles.py
  package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/linapple/linappleConfig.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/linapple/linappleGenerator.py
  package/batocera/core/batocera-configgen/datainit/linapple/Master.dsk
  package/batocera/core/batocera-system/Config.in
  package/batocera/emulationstation/batocera-es-system/es_systems.yml
  package/batocera/emulators/linapple-pie/linapple-pie.mk
  package/batocera/emulators/linapple/000-pathconf.patch
  package/batocera/emulators/linapple/Config.in
  package/batocera/emulators/linapple/linapple.mk
  package/batocera/utils/rpigpioswitch/rpi-pin356-power.py
  scripts/linux/checkPackagesUpdates.sh
Labels: 5.26

#1315 update package and patch (libretro)
  package/batocera/emulators/retroarch/libretro/libretro-4do/000-makefile.patch
  package/batocera/emulators/retroarch/libretro/libretro-genesisplusgx/000-makefile.patch
  package/batocera/emulators/retroarch/libretro/libretro-mupen64plus-next/000-makefile.patch
  package/batocera/emulators/retroarch/libretro/libretro-mupen64plus-next/libretro-mupen64plus-next.mk
  package/batocera/emulators/retroarch/libretro/libretro-parallel-n64/000-makefile.patch
Labels: 5.26
