Repository batocera-linux/batocera.linux, pull requests merged in 2020-08, with the labels that each got.

#2080 Bump reicast to May 30, 2020
  board/batocera/odroidn2/patches/qt5base/001-fix-eglfs-mali.patch
  board/batocera/odroidn2/patches/reicast/board-fix-mali.patch
  board/batocera/odroidn2/patches/reicast/board-fix-pcw-crash.patch
  board/batocera/odroidn2/patches/reicast/board-fix-sdl-gl.patch
  board/batocera/odroidn2/patches/reicast/board-fix-sdl-window.patch
  board/batocera/odroidn2/patches/reicast/board-fix-sound.patch
  board/batocera/odroidn2/patches/reicast/board-hidemouse.patch
  board/batocera/odroidxu4/patches/reicast/board-fix-mali.patch
  board/batocera/odroidxu4/patches/reicast/board-fix-pcw-crash.patch
  board/batocera/odroidxu4/patches/reicast/board-fix-sdl-gl.patch
  board/batocera/odroidxu4/patches/reicast/board-fix-sdl-window.patch
  board/batocera/odroidxu4/patches/reicast/board-fix-sound.patch
  board/batocera/odroidxu4/patches/reicast/board-hidemouse.patch
  board/batocera/rockchip/patches/reicast/board-fix-mali.patch
  board/batocera/rockchip/patches/reicast/board-fix-sdl-gl.patch
  board/batocera/rockchip/patches/reicast/board-fix-sdl-window.patch
  board/batocera/rockchip/patches/reicast/board-hidemouse.patch
  board/batocera/rockchip/rk3288/patches/reicast/board-fix-pcw-crash.patch
  board/batocera/rockchip/rk3288/patches/reicast/board-fix-sound.patch
  board/batocera/rockchip/rk3399/patches/reicast/board-fix-pcw-crash.patch
  board/batocera/rockchip/rk3399/patches/reicast/board-fix-sound.patch
  package/batocera/emulators/reicast/000-makefile.patch.disabled
  package/batocera/emulators/reicast/001-biospath.patch
  package/batocera/emulators/reicast/002-hotkey.patch
  package/batocera/emulators/reicast/003-alsasound.patch
  package/batocera/emulators/reicast/004-multipleinputs.patch.disabled
  package/batocera/emulators/reicast/reicast.mk
Labels: 5.28

#2089 Bump mali-bifrost-module to r25p0-eac0
  package/batocera/gpu/mali-bifrost-module/mali-bifrost-module.mk
Labels: 5.28

#2096 Bump nvidia driver 450.57
  package/batocera/gpu/batocera-nvidia-driver/nvidia-driver.mk
Labels: 5.28

#2100 More fixes
  board/batocera/post-image-script.sh
  board/batocera/vim3/genimage.cfg
  package/batocera/core/batocera-configgen/batocera-configgen.mk
  package/batocera/emulators/retroarch/libretro/libretro-mame/libretro-mame.mk
Labels: 5.27

#2102 fix: pacman lock file (5.27)
  package/batocera/core/batocera-scripts/scripts/batocera-store
Labels: don't merge

#2125 batocera-audio: remove pulseaudio and persist alsa state
  batocera-Changelog
  board/batocera/fsoverlay/etc/init.d/S65values4boot
  board/batocera/patches/alsa-lib/001-read-asoundrc-boot.patch
  package/batocera/core/batocera-audio/500ms-of-silence.wav
  package/batocera/core/batocera-audio/Config.in
  package/batocera/core/batocera-audio/S01audio
  package/batocera/core/batocera-audio/S15audio
  package/batocera/core/batocera-audio/alsa/batocera-audio
  package/batocera/core/batocera-audio/batocera-audio.mk
  package/batocera/core/batocera-audio/pulseaudio/batocera-audio
  package/batocera/core/batocera-audio/pulseaudio/client.conf
  package/batocera/core/batocera-audio/pulseaudio/default.pa
  package/batocera/core/batocera-audio/soundconfig
  package/batocera/core/batocera-system/c2/batocera.conf
  package/batocera/core/batocera-system/libretech_h5/batocera.conf
  package/batocera/core/batocera-system/miqi/batocera.conf
  package/batocera/core/batocera-system/odroidgoa/batocera.conf
  package/batocera/core/batocera-system/odroidn2/batocera.conf
  package/batocera/core/batocera-system/rock960/batocera.conf
  package/batocera/core/batocera-system/rockpro64/batocera.conf
  package/batocera/core/batocera-system/rpi1/batocera.conf
  package/batocera/core/batocera-system/rpi2/batocera.conf
  package/batocera/core/batocera-system/rpi3/batocera.conf
  package/batocera/core/batocera-system/rpi4/batocera.conf
  package/batocera/core/batocera-system/s905/batocera.conf
  package/batocera/core/batocera-system/s912/batocera.conf
  package/batocera/core/batocera-system/tinkerboard/batocera.conf
  package/batocera/core/batocera-system/vim3/batocera.conf
  package/batocera/core/batocera-system/x86/batocera.conf
  package/batocera/core/batocera-system/x86_64/batocera.conf
  package/batocera/core/batocera-system/xu4/batocera.conf
Labels: 5.27
