Repository batocera-linux/batocera.linux, pull requests merged in 2020-06, with the labels that each got.

#1818 Add new widescreen hack options
  package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinControllers.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
  package/batocera/emulationstation/batocera-es-system/batocera-es-system.mk
  package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
  package/batocera/emulationstation/batocera-es-system/es_features.yml
Labels: don't merge

#1831 batocera-es-system update
  package/batocera/emulationstation/batocera-es-system/batocera-es-system.py
  package/batocera/emulationstation/batocera-es-system/es_features.yml
Labels: conflicts

#1866 Enable pulseaudio for all boards
  Makefile
  board/batocera/vim3/fsoverlay/usr/share/alsa/cards/AMLG12.conf
  board/batocera/vim3/fsoverlay/usr/share/alsa/cards/G12-HDMI.conf
  board/batocera/vim3/patches/uboot/0090-VIM3x_enable_HDMI_output.patch
  board/batocera/vim3/patches/uboot/0091-VIM3x_hdmi_fix_dts.patch
  board/batocera/vim3/patches/uboot/0092-VIM3x_GPIOD_OPEN_DRAIN_hdmi_fix.patch
  board/batocera/vim3/uboot-defconfig-fragment.config
  configs/batocera-rockpro64_defconfig
  configs/batocera-vim3_defconfig
  package/batocera/core/batocera-audio/90-alsa-setup.rules
  package/batocera/core/batocera-audio/Config.in
  package/batocera/core/batocera-audio/S15audio
  package/batocera/core/batocera-audio/asound.conf.dmix
  package/batocera/core/batocera-audio/batocera-audio
  package/batocera/core/batocera-audio/batocera-audio-dmix
  package/batocera/core/batocera-audio/batocera-audio-none
  package/batocera/core/batocera-audio/batocera-audio-odroidgoa
  package/batocera/core/batocera-audio/batocera-audio-pulseaudio
  package/batocera/core/batocera-audio/batocera-audio-rpi
  package/batocera/core/batocera-audio/batocera-audio-vim3
  package/batocera/core/batocera-audio/batocera-audio.mk
  package/batocera/core/batocera-audio/soundconfig
  package/batocera/core/batocera-system/Config.in
  package/batocera/libraries/alsa-plugins/alsa-plugins.mk
Labels: 5.27

#1850 H5: add batocera post-image layout
  board/batocera/libretech-h5/boot/extlinux.conf
  board/batocera/libretech-h5/genimage.cfg
  board/batocera/libretech-h5/linux-defconfig.config
  board/batocera/libretech-h5/patches/batocera-emulationstation/001-EGL.patch
  board/batocera/post-image-script.sh
  configs/batocera-libretech-h5_defconfig
  package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk
  package/batocera/emulators/amiberry/amiberry.mk
  package/batocera/emulators/retroarch/libretro/libretro-flycast/libretro-flycast.mk
Labels: 5.27, don't merge
