Repository batocera-linux/batocera.linux, pull requests merged in 2023-12, with the labels that each got.

#10536 add support for retro shooter lightguns
  Config.in
  package/batocera/controllers/retroshooter-guns/99-retroshooter-guns.rules
  package/batocera/controllers/retroshooter-guns/Config.in
  package/batocera/controllers/retroshooter-guns/retroshooter-guns-add
  package/batocera/controllers/retroshooter-guns/retroshooter-guns.mk
Labels: WIP

#8191 batocera-scripts / batocera-info updated to report V_BOARD as board
  package/batocera/core/batocera-scripts/scripts/batocera-info
Labels: conflicts

#10625 Support CONFIGS@ mount point in S11share
  board/batocera/fsoverlay/etc/init.d/S11share
Labels: feature request, feedback

#10680 Support open wifi network without passphrase
  board/batocera/fsoverlay/etc/init.d/S08connman
Labels: discord-request

#10679 support sonic origins releases for sonicretro
  package/batocera/core/batocera-configgen/configgen/configgen/generators/sonicretro/sonicretroGenerator.py
Labels: enhancement, discord request
