Repository batocera-linux/batocera.linux, pull requests merged in 2024-12, with the labels that each got.

#13019 typos on changelog
  batocera-Changelog.md
Labels: 41

#13062 Check in batocera-boot.conf for luks.enabled before share is mounted
  board/batocera/fsoverlay/etc/init.d/S11share
Labels: 41

#12998 Save random seed on startup [v42]
  board/batocera/fsoverlay/etc/init.d/S03urandom
Labels: 42

#12993 fix batocera-usbmount [V41 or V42?]
  package/batocera/core/batocera-scripts/scripts/batocera-usbmount
Labels: 42

#12990 Update S18governor [V42]
  board/batocera/fsoverlay/etc/init.d/S18governor
Labels: 42

#12925 add image scaling to drastic [V42]
  package/batocera/core/batocera-configgen/configgen/configgen/generators/drastic/drasticGenerator.py
  package/batocera/emulationstation/batocera-es-system/es_features.yml
Labels: 42

#13117 gambette core: add game-specific palette option
  package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
  package/batocera/emulationstation/batocera-es-system/es_features.yml
Labels: 42

#13116 enable DuckStation cheat list
  package/batocera/core/batocera-configgen/configgen/configgen/generators/duckstation/duckstationGenerator.py
  package/batocera/emulationstation/batocera-es-system/es_features.yml
Labels: 42

#13115 Update es_input.cfg
  package/batocera/emulationstation/batocera-emulationstation/controllers/es_input.cfg
Labels: 42

#13067 fix gsplus rom config and speed
  package/batocera/core/batocera-configgen/configgen/configgen/generators/gsplus/gsplusGenerator.py
Labels: 42

#13060 Added SGB-MSU1 with squashfs
  package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
  package/batocera/core/batocera-configgen/configs/configgen-defaults.yml
  package/batocera/emulationstation/batocera-es-system/es_systems.yml
Labels: 42

#13058 Fix MAME config for apple2p, apple2e, apple2ee
  package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
Labels: 42

#12997 RK3326: Add WireGuard
  batocera-Changelog.md
  board/batocera/rockchip/rk3326/linux_patches/0022-add-wireguard.patch
  package/batocera/core/batocera-system/Config.in
Labels: 42

#12991 wifi-update [V42]
  board/batocera/fsoverlay/etc/init.d/S08connman
  package/batocera/core/batocera-scripts/scripts/batocera-wifi
Labels: 42

#13086 add non-micro gun4ir hardware
  package/batocera/controllers/guns/gun4ir-guns/99-gun4ir.rules
Labels: 42

#13094 Add support for RS3 Reaper (new retro shooter light gun model)
  package/batocera/controllers/guns/retroshooter-guns/99-retroshooter-guns.rules
  package/batocera/controllers/guns/retroshooter-guns/retroshooter-guns-add
Labels: WIP, 42

#13064 refactor configgen invocation of batocera-vulkan into module
  package/batocera/core/batocera-configgen/configgen/configgen/generators/cemu/cemuGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/citra/citraGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/dolphin/dolphinGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/lemonade/lemonadeGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/pcsx2/pcsx2Generator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/ppsspp/ppssppConfig.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/rpcs3/rpcs3Generator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/shadps4/shadps4Generator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/suyu/suyuGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/utils/vulkan.py
Labels: 42

#13165 refactor configgen wine invocations into module
  package/batocera/core/batocera-configgen/configgen/configgen/generators/fpinball/fpinballGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/model2emu/model2emuGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/generators/xenia/xeniaGenerator.py
  package/batocera/core/batocera-configgen/configgen/configgen/utils/wine.py
Labels: 42
